# Generated by Django 5.0.6 on 2024-06-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='friday',
            field=models.CharField(blank=True, help_text='время формата: 00:00-24:00', max_length=255),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='monday',
            field=models.CharField(blank=True, help_text='время формата: 00:00-24:00', max_length=255),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='saturday',
            field=models.CharField(blank=True, help_text='время формата: 00:00-24:00', max_length=255),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='sunday',
            field=models.CharField(blank=True, help_text='время формата: 00:00-24:00', max_length=255),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='thursday',
            field=models.CharField(blank=True, help_text='время формата: 00:00-24:00', max_length=255),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='tuesday',
            field=models.CharField(blank=True, help_text='время формата: 00:00-24:00', max_length=255),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='wednesday',
            field=models.CharField(blank=True, help_text='время формата: 00:00-24:00', max_length=255),
        ),
    ]
