# Generated by Django 5.0.6 on 2024-06-05 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0002_alter_worktime_friday_alter_worktime_monday_and_more'),
        ('user', '0010_alter_favorites_options_alter_reviews_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('profile_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profilemaster')),
                ('specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.specialist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'запись',
            },
        ),
    ]
