# Generated by Django 5.0.6 on 2024-06-17 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0004_recording_date_recording_date_create'),
        ('user', '0014_profilemaster_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktime',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.specialist'),
        ),
    ]
