# Generated by Django 5.0.6 on 2024-06-17 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0005_worktime_specialist'),
        ('user', '0014_profilemaster_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profilemaster', verbose_name='профиль'),
        ),
    ]
