# Generated by Django 5.0.6 on 2024-06-17 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0008_remove_worktime_service_recording_service'),
        ('user', '0014_profilemaster_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='profile_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profilemaster'),
        ),
    ]
