# Generated by Django 5.0.6 on 2024-07-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0010_alter_recording_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recording',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер'),
        ),
        migrations.AddField(
            model_name='recording',
            name='surname',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Фамилия'),
        ),
    ]
