# Generated by Django 5.0.6 on 2024-07-22 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0011_recording_name_recording_phone_recording_surname'),
        ('user', '0019_alter_profilemaster_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='profile_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_recordings', to='user.profilemaster'),
        ),
        migrations.DeleteModel(
            name='WorkTime',
        ),
    ]
