# Generated by Django 5.0.6 on 2024-07-22 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0012_alter_recording_profile_master_delete_worktime'),
        ('user', '0019_alter_profilemaster_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('break_time', models.TimeField(default='00:30:00', verbose_name='время перерыва')),
                ('profile_master', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_times', to='user.profilemaster', verbose_name='Профиль мастера')),
                ('specialist', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_times', to='user.specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Рабочее время',
            },
        ),
    ]
