# Generated by Django 5.0.6 on 2024-07-22 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0014_alter_worktime_date'),
        ('user', '0019_alter_profilemaster_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='profile_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_times', to='user.profilemaster', verbose_name='Профиль мастера'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_times', to='user.specialist', verbose_name='Специалист'),
        ),
    ]
