# Generated by Django 5.0.6 on 2024-07-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0015_alter_worktime_profile_master_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktime',
            name='time_work',
            field=models.CharField(default='wad', help_text='формат 00:00-24:00', max_length=15, verbose_name='рабочее время'),
        ),
    ]
