# Generated by Django 5.0.6 on 2024-07-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0016_worktime_time_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='time_work',
            field=models.CharField(help_text='формат 00:00-24:00', max_length=15, verbose_name='рабочее время'),
        ),
    ]
