# Generated by Django 5.0.6 on 2024-07-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0017_alter_worktime_time_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='break_time',
            field=models.CharField(blank=True, help_text='формат 00:00-24:00', max_length=15, verbose_name='время перерыва'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='date',
            field=models.DateField(verbose_name='дата'),
        ),
    ]
