# Generated by Django 5.0.6 on 2024-05-29 11:13

import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='photo',
            field=models.ImageField(blank=True, upload_to=service.models.upload_photo_service, verbose_name='изображение'),
        ),
    ]
