# Generated by Django 5.0.6 on 2024-05-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='photo',
            field=models.ImageField(upload_to='static/media/categories/', verbose_name='изображение'),
        ),
    ]
