# Generated by Django 5.0.6 on 2024-05-31 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_service_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='user',
            new_name='profile',
        ),
    ]
