# Generated by Django 5.0.6 on 2024-05-31 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_rename_user_service_profile'),
        ('user', '0005_specialist_alter_profileimages_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialist_services', to='user.specialist', verbose_name='специалист'),
        ),
        migrations.AlterField(
            model_name='service',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_services', to='user.profilemaster', verbose_name='профиль мастера'),
        ),
    ]
