# Generated by Django 5.0.6 on 2024-06-10 12:53

import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_service_specialist_alter_service_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='photo',
            field=models.ImageField(upload_to=service.models.upload_photo_service, verbose_name='изображение'),
        ),
    ]
