# Generated by Django 5.0.6 on 2024-06-11 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_alter_service_photo'),
        ('user', '0013_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.categories', verbose_name='категория'),
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
