# Generated by Django 5.0.6 on 2024-06-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_service_category_delete_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='время процедуры'),
        ),
    ]
