# Generated by Django 5.0.6 on 2024-07-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_alter_service_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.TimeField(verbose_name='время процедуры'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=255, verbose_name='заголовок'),
        ),
    ]
