# Generated by Django 5.0.6 on 2024-05-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='specialization',
            field=models.CharField(blank=True, choices=[('Мастер', 'мастер'), ('Студия', 'студия'), ('Клиент', 'клиент')], max_length=10, verbose_name='специализация'),
        ),
    ]
