# Generated by Django 5.0.6 on 2024-05-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_specialist_alter_profileimages_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemaster',
            name='specialization',
            field=models.CharField(choices=[('master', 'мастер'), ('studio', 'студия')], default='master', max_length=25, verbose_name='специализация'),
        ),
    ]
