# Generated by Django 5.0.6 on 2024-05-29 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profilemaster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilemaster',
            options={'verbose_name': 'Профиль мастера/студия', 'verbose_name_plural': 'Профили мастеров/студий'},
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='заголовок')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('price', models.IntegerField(blank=True, verbose_name='цена')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
            },
        ),
    ]
