# Generated by Django 5.0.6 on 2024-05-31 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profilemaster_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_specialist', to='user.profilemaster', verbose_name='специалист'),
        ),
    ]
