# Generated by Django 5.0.6 on 2024-05-29 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profilemaster_options_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
