# Generated by Django 5.0.6 on 2024-06-03 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_specialist_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimages',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_services', to='user.specialist', verbose_name='специалист'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_specialist', to='user.profilemaster', verbose_name='профиль'),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_star', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default='5', max_length=1, verbose_name='кол-во звезд')),
                ('description', models.TextField(verbose_name='описание')),
                ('data_create', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_profile', to='user.profilemaster', verbose_name='профиль мастера/студии')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
    ]
