# Generated by Django 5.0.6 on 2024-06-10 06:07

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_favorites_options_alter_reviews_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemaster',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.upload_photo_profile),
        ),
    ]
