# Generated by Django 5.0.6 on 2024-06-10 06:22

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_profilemaster_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimages',
            name='image',
            field=models.ImageField(upload_to=user.models.upload_photo_profile_services, verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='profilemaster',
            name='photo',
            field=models.ImageField(upload_to=user.models.upload_photo_profile),
        ),
    ]
