# Generated by Django 5.0.6 on 2024-06-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemaster',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='user.categories'),
        ),
    ]
