# Generated by Django 5.0.6 on 2024-06-29 04:50

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_profilemaster_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(default='media/users/default.jpg', upload_to=user.models.upload_photo_user),
        ),
    ]
