# Generated by Django 5.0.6 on 2024-06-29 05:21

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_customuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='photo',
            field=models.ImageField(default='media/specialist/default.jpg', upload_to=user.models.upload_photo_specialist, verbose_name='аватарка'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(default='media/users/default.jpg', upload_to=user.models.upload_photo_user, verbose_name='аватарка'),
        ),
    ]
