# Generated by Django 5.0.6 on 2024-09-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_profilemaster_time_relax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='job',
            field=models.CharField(blank=True, max_length=50, verbose_name='кфалификация'),
        ),
    ]
